### ISSUE TITLE
Map tiles not loading correctly on first load after install of application (previously titled Moving map)

### ISSUE THREAD

**Issue by jm42** [canyouswim/Caching-on-Kai#13]
I installed the app in a Nokia 8110 4G, and the map starts in the upper left corner, like this:

![Map in the upper left corner](https://user-images.githubusercontent.com/3297150/97931764-fb34a100-1d33-11eb-8cdd-3f11132e73f1.png)

Then I move, and moves weird.

![catching-map-1](https://user-images.githubusercontent.com/3297150/97931761-fa9c0a80-1d33-11eb-92cb-6317cbedac21.png)

And when pressing **CENTER**, it does this:

![catching-map-2](https://user-images.githubusercontent.com/3297150/97931758-f96add80-1d33-11eb-8a66-5ba5a01115c2.png)

Would be nice if the map stays in one place, or just cover the whole screen space.

**Comment by canyouswim** [comment]
will check into this as well - it should fill the entire screen.

**Comment by canyouswim** [comment]
digging into this - it looks like all the map tiles are not loading on your device for some reason - i'm having a hard time reproducing it on on my side, but it's clearly happening for you.  How is your data connection?  if you zoom in (3) or out (1) does that make any difference?

**Comment by canyouswim** [comment]
just for grins, in case this does not resolve on its own (fingers crossed), can you send me your rough GPS coords?  i doubt it, but just in case the map location plays into this at all

**Comment by jm42** [comment]
> map tiles are not loading on your device

Yes. This seems to be the problem. I try it again this morning and works well now. A little slow, loading map tiles and caches.. and then waiting until caches refresh. But eventually it worked.

**Comment by canyouswim** [comment]
btw - i was finally able to reproduce this issue, so i'm re-opening the ticket for further investigation.  it _seems_ to be related to the very first load after installing the app, as i have not been able to get it to happen again if i close the app and reopen, from that point forward.  regardless, good to look into.

**Comment by canyouswim** [comment]
it looks like this happens when there is some other window/action on the screen when the map tiles are drawn for the first time.  for instance, when you first load the app, the OS prompts you for permission to use the GPS.  this is an overlay on top of the app, and the map tiles get thrown off by it (not setting their (0,0) location correctly in the window).  this can also be reproduced after the initial time of installing the app by quickly pressing the Options softkey while the GPS is still getting a lock. 

I need to figure out why this is happening.  the easiest hack fix is to exit and restart the app and not do anything until the map is drawn, but this is in-elegant and not user friendly...

**Comment by canyouswim** [comment]
this should be resolved now in v2.1.1
