### ISSUE TITLE
error with premium caches

### ISSUE THREAD

**Issue by david-p-s** [canyouswim/Caching-on-Kai#16]
The list of caches doesn't work when a premium cache is present. I've solved it by adding this IF in the loop:

		        var CachePremium = geoCacheDetails[i].hasAttribute("data-premium");

					if (CachePremium == false)	{
						var CacheName = geoCacheDetails[i].getElementsByClassName("cache-name");
						(... lots of lines....)
						listContainer.appendChild(entry);
					 }

**Comment by canyouswim** [comment]
do you have a premium account?  non-premium users is an area i haven't really tested yet, as i have a premium account.  i think i'll need to add another catch to see if the user is logged in with a premium account, and then filter the list of caches appropriately as you noted.

**Comment by canyouswim** [comment]
this is done!  pull down the latest here - https://github.com/canyouswim/Caching-on-Kai/releases/download/v1.1.0/caching-on-kai.zip (also submitted to app store).  i'll clean up the styling a bit later, but wanted to get this out to you sooner rather than later :)

**Comment by david-p-s** [comment]
> 
> 
> this is done! pull down the latest here - https://github.com/canyouswim/Caching-on-Kai/releases/download/v1.1.0/caching-on-kai.zip (also submitted to app store). i'll clean up the styling a bit later, but wanted to get this out to you sooner rather than later :)

Nice! It works perfectly :-)

Thank you a lot!

**Comment by canyouswim** [comment]
awesome!  happy caching :)  are you metric or imperial units based?  that's next on my more immediate punch list of features is to create a setting screen to control the displayed units (right now it's imperial)

**Comment by david-p-s** [comment]
All over the world except in the country now governed by Biden we use the Metric System. I changed it myself "by default" before installing ;-)

But I did it only in the UI, because I think I can miss something in the distance algorithms:

		if(tripDistance < .5) {
			mapContent = mapContent + `${roundToTwo(tripDistance * 5280 * 0.3048)}m`;
			distToCache.innerHTML = `<b>Distance</b></br>${roundToTwo(tripDistance * 0.3048)}m`;
		} else {
			mapContent = mapContent + `${roundToTwo(tripDistance * 1.60934)}km`;
			distToCache.innerHTML = `<b>Distance</b></br>${roundToTwo(tripDistance * 1.60934)}km`;
		};

**Comment by canyouswim** [comment]
if you're cool playing in the code for a short while, here are the places to pay attention to:

- in function findDistance, at the end, just change it up to "return km" instead of "return mi"
	// round the results down to the nearest 1/1000
	mi = round(dm);
	km = round(dk);

	**return** mi;

- and you found the other place where i convert to feet from miles if we're close enough - so just tweak that conversion factor to account for meters instead of feet.

or you can probably just leave it the way you did :)

**Comment by canyouswim** [comment]
i'll probably simplify the code to do the feet/meters vs. miles/km calc in the findDistance function to make life easier down the road and simplify the switch for US vs. everyone else who is sane in the world and likes things easy...

**Comment by canyouswim** [comment]
exciting times!  v1.2.0 is here - https://github.com/canyouswim/Caching-on-Kai/releases/download/v1.2.0/caching-on-kai.zip - now with a persistent display units toggle!  _and_ refreshing the cache list will now pull the list of 50 closes caches based on wherever the map is focused, instead of always your current position (so you can make decisions on where to cache next outside of your immediate current area) :)
