### ISSUE TITLE
v1.4 bug

### ISSUE THREAD

**Issue by david-p-s** [canyouswim/Caching-on-Kai#43]
I can't load the details page of any cache. It's because the array don't exists. It works if you push();
						//arrayCache[CacheCount] = arrayCacheObject;
						arrayCache.push(arrayCacheObject);

If I where you, I will use tow arrays:

1. To create firstly the string:    	arrayCache_2.push(arrayCacheObject);
2. and then reorder it:
    	for(var i=0;i<arrayCache_2.length;i++){
    		arayCache.push(arrayCache[i]);   
    	}

**Comment by canyouswim** [comment]
Dang sorry about that - was too fast in releasing.  Will fix that this morning.  Going forward - how do you feel about running a test on my work before it gets merged to master and released?  More eyes and all?canyouswim/Caching-on-Kai wrote:
I can't load the details page of any cache. It's because the array don't exists. It works if you push();
//arrayCache[CacheCount] = arrayCacheObject;
arrayCache.push(arrayCacheObject);
If I where you, I will use tow arrays:

To create firstly the string:    	arrayCache_2.push(arrayCacheObject);
and then reorder it:
for(var i=0;i<arrayCache_2.length;i++){
arayCache.push(arrayCache[i]);
}

**Comment by canyouswim** [comment]
kk - this is fixed now in v1.4.1.  going forward, i'll put a request in for you to review my pull requests :)  that way we can have a second set of eyes on my code changes.  i have a tendency to forget to check for limited functionality in non-premium accounts... :(
